app:
  env: dev
  name: go-mall
  addr: :9000
  log:
    path: "/tmp/applog/go-mall.log"
    max_size: 100
    max_age: 90
  pagination:
    default_size: 20
    max_size: 100
database:
  master:
    type: mysql
    dsn: root:411122@tcp(localhost:30306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    max_open: 100
    max_idle: 10
    max_lifetime: 300000000 # 300s 内可复用
  slave:
    type: mysql
    dsn: root:411122@tcp(localhost:30306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    max_open: 100
    max_idle: 10
    max_lifetime: 300000000

