app:
  env: dev
  name: go-mall
  log:
    path: "/tmp/applog/go-mall.log"
    max_size: 100
    max_age: 90
database:
  type: mysql
  dsn: "reserved"
  max_open: 100
  max_idle: 10
  max_lifetime: 300
pagination:
  default_size: 20
  max_size: 100