app:
  env: test
  name: go-mall
  log:
    path: "/tmp/applog/go-mall.log" #生产环境放在固定目录可以让ELK日志收集组件统一到日志平台
    max_size: 100
    max_age: 90
  pagination:
    default_size: 20
    max_size: 100
database:
  type: mysql
  dsn: "reserved"
  maxopen: 100
  maxidle: 10
  maxlifetime: 300